# -*- coding: utf-8 -*-
"""CarvaluePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QMmdhZsOwBpPZH8GAFbH3zajoB1su7O
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

data = {
    'Mileage': [50000, 80000, 20000, 60000, 30000, 70000, 10000, 90000, 40000, 55000],
    'Age': [5, 7, 2, 4, 3, 6, 1, 8, 4, 5],
    'Engine_Power': [150, 120, 200, 180, 160, 140, 220, 100, 190, 170],
    'Price': [20000, 18000, 25000, 22000, 23000, 21000, 27000, 15000, 24000, 22500]
}

df = pd.DataFrame(data)

X = df[['Mileage', 'Age', 'Engine_Power']]
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')


new_vehicle = {'Mileage': 40000, 'Age': 3, 'Engine_Power': 170}
new_vehicle_df = pd.DataFrame([new_vehicle])
prediction = model.predict(new_vehicle_df)
print(f'Predicted Price: {prediction[0]}')
print('Piyush Wattakhare');
print('Sarvesh Wwadaskar');
print('Aniket Dhenge');
print('Ekta Narnaware');
print('Jayesh Manhohare')